require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FinunitsController do

  # This should return the minimal set of attributes required to create a valid
  # Finunit. As you add validations to Finunit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all finunits as @finunits" do
      finunit = Finunit.create! valid_attributes
      get :index
      assigns(:finunits).should eq([finunit])
    end
  end

  describe "GET show" do
    it "assigns the requested finunit as @finunit" do
      finunit = Finunit.create! valid_attributes
      get :show, :id => finunit.id.to_s
      assigns(:finunit).should eq(finunit)
    end
  end

  describe "GET new" do
    it "assigns a new finunit as @finunit" do
      get :new
      assigns(:finunit).should be_a_new(Finunit)
    end
  end

  describe "GET edit" do
    it "assigns the requested finunit as @finunit" do
      finunit = Finunit.create! valid_attributes
      get :edit, :id => finunit.id.to_s
      assigns(:finunit).should eq(finunit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Finunit" do
        expect {
          post :create, :finunit => valid_attributes
        }.to change(Finunit, :count).by(1)
      end

      it "assigns a newly created finunit as @finunit" do
        post :create, :finunit => valid_attributes
        assigns(:finunit).should be_a(Finunit)
        assigns(:finunit).should be_persisted
      end

      it "redirects to the created finunit" do
        post :create, :finunit => valid_attributes
        response.should redirect_to(Finunit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved finunit as @finunit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finunit.any_instance.stub(:save).and_return(false)
        post :create, :finunit => {}
        assigns(:finunit).should be_a_new(Finunit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finunit.any_instance.stub(:save).and_return(false)
        post :create, :finunit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested finunit" do
        finunit = Finunit.create! valid_attributes
        # Assuming there are no other finunits in the database, this
        # specifies that the Finunit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Finunit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => finunit.id, :finunit => {'these' => 'params'}
      end

      it "assigns the requested finunit as @finunit" do
        finunit = Finunit.create! valid_attributes
        put :update, :id => finunit.id, :finunit => valid_attributes
        assigns(:finunit).should eq(finunit)
      end

      it "redirects to the finunit" do
        finunit = Finunit.create! valid_attributes
        put :update, :id => finunit.id, :finunit => valid_attributes
        response.should redirect_to(finunit)
      end
    end

    describe "with invalid params" do
      it "assigns the finunit as @finunit" do
        finunit = Finunit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finunit.any_instance.stub(:save).and_return(false)
        put :update, :id => finunit.id.to_s, :finunit => {}
        assigns(:finunit).should eq(finunit)
      end

      it "re-renders the 'edit' template" do
        finunit = Finunit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finunit.any_instance.stub(:save).and_return(false)
        put :update, :id => finunit.id.to_s, :finunit => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested finunit" do
      finunit = Finunit.create! valid_attributes
      expect {
        delete :destroy, :id => finunit.id.to_s
      }.to change(Finunit, :count).by(-1)
    end

    it "redirects to the finunits list" do
      finunit = Finunit.create! valid_attributes
      delete :destroy, :id => finunit.id.to_s
      response.should redirect_to(finunits_url)
    end
  end

end
