require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LoadingsController do

  # This should return the minimal set of attributes required to create a valid
  # Loading. As you add validations to Loading, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all loadings as @loadings" do
      loading = Loading.create! valid_attributes
      get :index
      assigns(:loadings).should eq([loading])
    end
  end

  describe "GET show" do
    it "assigns the requested loading as @loading" do
      loading = Loading.create! valid_attributes
      get :show, :id => loading.id.to_s
      assigns(:loading).should eq(loading)
    end
  end

  describe "GET new" do
    it "assigns a new loading as @loading" do
      get :new
      assigns(:loading).should be_a_new(Loading)
    end
  end

  describe "GET edit" do
    it "assigns the requested loading as @loading" do
      loading = Loading.create! valid_attributes
      get :edit, :id => loading.id.to_s
      assigns(:loading).should eq(loading)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Loading" do
        expect {
          post :create, :loading => valid_attributes
        }.to change(Loading, :count).by(1)
      end

      it "assigns a newly created loading as @loading" do
        post :create, :loading => valid_attributes
        assigns(:loading).should be_a(Loading)
        assigns(:loading).should be_persisted
      end

      it "redirects to the created loading" do
        post :create, :loading => valid_attributes
        response.should redirect_to(Loading.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved loading as @loading" do
        # Trigger the behavior that occurs when invalid params are submitted
        Loading.any_instance.stub(:save).and_return(false)
        post :create, :loading => {}
        assigns(:loading).should be_a_new(Loading)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Loading.any_instance.stub(:save).and_return(false)
        post :create, :loading => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested loading" do
        loading = Loading.create! valid_attributes
        # Assuming there are no other loadings in the database, this
        # specifies that the Loading created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Loading.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => loading.id, :loading => {'these' => 'params'}
      end

      it "assigns the requested loading as @loading" do
        loading = Loading.create! valid_attributes
        put :update, :id => loading.id, :loading => valid_attributes
        assigns(:loading).should eq(loading)
      end

      it "redirects to the loading" do
        loading = Loading.create! valid_attributes
        put :update, :id => loading.id, :loading => valid_attributes
        response.should redirect_to(loading)
      end
    end

    describe "with invalid params" do
      it "assigns the loading as @loading" do
        loading = Loading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Loading.any_instance.stub(:save).and_return(false)
        put :update, :id => loading.id.to_s, :loading => {}
        assigns(:loading).should eq(loading)
      end

      it "re-renders the 'edit' template" do
        loading = Loading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Loading.any_instance.stub(:save).and_return(false)
        put :update, :id => loading.id.to_s, :loading => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested loading" do
      loading = Loading.create! valid_attributes
      expect {
        delete :destroy, :id => loading.id.to_s
      }.to change(Loading, :count).by(-1)
    end

    it "redirects to the loadings list" do
      loading = Loading.create! valid_attributes
      delete :destroy, :id => loading.id.to_s
      response.should redirect_to(loadings_url)
    end
  end

end
