require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PayoffsController do

  # This should return the minimal set of attributes required to create a valid
  # Payoff. As you add validations to Payoff, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all payoffs as @payoffs" do
      payoff = Payoff.create! valid_attributes
      get :index
      assigns(:payoffs).should eq([payoff])
    end
  end

  describe "GET show" do
    it "assigns the requested payoff as @payoff" do
      payoff = Payoff.create! valid_attributes
      get :show, :id => payoff.id.to_s
      assigns(:payoff).should eq(payoff)
    end
  end

  describe "GET new" do
    it "assigns a new payoff as @payoff" do
      get :new
      assigns(:payoff).should be_a_new(Payoff)
    end
  end

  describe "GET edit" do
    it "assigns the requested payoff as @payoff" do
      payoff = Payoff.create! valid_attributes
      get :edit, :id => payoff.id.to_s
      assigns(:payoff).should eq(payoff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Payoff" do
        expect {
          post :create, :payoff => valid_attributes
        }.to change(Payoff, :count).by(1)
      end

      it "assigns a newly created payoff as @payoff" do
        post :create, :payoff => valid_attributes
        assigns(:payoff).should be_a(Payoff)
        assigns(:payoff).should be_persisted
      end

      it "redirects to the created payoff" do
        post :create, :payoff => valid_attributes
        response.should redirect_to(Payoff.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payoff as @payoff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payoff.any_instance.stub(:save).and_return(false)
        post :create, :payoff => {}
        assigns(:payoff).should be_a_new(Payoff)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payoff.any_instance.stub(:save).and_return(false)
        post :create, :payoff => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payoff" do
        payoff = Payoff.create! valid_attributes
        # Assuming there are no other payoffs in the database, this
        # specifies that the Payoff created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Payoff.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => payoff.id, :payoff => {'these' => 'params'}
      end

      it "assigns the requested payoff as @payoff" do
        payoff = Payoff.create! valid_attributes
        put :update, :id => payoff.id, :payoff => valid_attributes
        assigns(:payoff).should eq(payoff)
      end

      it "redirects to the payoff" do
        payoff = Payoff.create! valid_attributes
        put :update, :id => payoff.id, :payoff => valid_attributes
        response.should redirect_to(payoff)
      end
    end

    describe "with invalid params" do
      it "assigns the payoff as @payoff" do
        payoff = Payoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payoff.any_instance.stub(:save).and_return(false)
        put :update, :id => payoff.id.to_s, :payoff => {}
        assigns(:payoff).should eq(payoff)
      end

      it "re-renders the 'edit' template" do
        payoff = Payoff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payoff.any_instance.stub(:save).and_return(false)
        put :update, :id => payoff.id.to_s, :payoff => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payoff" do
      payoff = Payoff.create! valid_attributes
      expect {
        delete :destroy, :id => payoff.id.to_s
      }.to change(Payoff, :count).by(-1)
    end

    it "redirects to the payoffs list" do
      payoff = Payoff.create! valid_attributes
      delete :destroy, :id => payoff.id.to_s
      response.should redirect_to(payoffs_url)
    end
  end

end
